
FROM docker.elastic.co/elasticsearch/elasticsearch:9.0.0
# COPY /roles /roles
# COPY /entrypoint.sh /entrypoint.sh
# COPY /lib.sh /lib.sh

# RUN chmod +x /entrypoint.sh \
#     && chmod +x /lib.sh
ENTRYPOINT ["/entrypoint.sh"]


